# Random Data Distribution

#### @jabedkhanjb

# What is Data Distribution?

Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

# Random Distribution

A random distribution is a set of random numbers that follow a certain probability density function.

We can generate random numbers based on defined probabilities using the <b>choice()</b> method of the <b>random</b> module.

The <b>choice()</b> method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

Generate a 1-D array containing 100 values, where each value has to be 1, 2, 3, 4.

The probability for the value to be 1 is set to be 0.5

The probability for the value to be 2 is set to be 0.3

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 4 is set to be 0.1

Summation of Probability should be 1 else code would be error.

In [21]:
from numpy import random

x = random.choice([1,2,3,4], p=[0.5, 0.3, 0.1, 0.1], size=(100))

print(x)

[1 2 1 2 1 1 1 2 2 1 1 1 2 1 2 3 1 1 2 1 1 1 4 3 1 2 2 2 4 4 3 1 1 1 4 1 1
 1 4 4 3 1 1 1 4 2 2 1 4 2 2 1 2 1 1 1 2 3 1 1 4 2 1 2 1 2 1 1 2 4 1 1 1 1
 4 1 4 1 1 1 1 1 1 4 2 3 3 4 2 4 1 1 2 1 2 3 4 2 1 2]


<b>The sum of all probability numbers should be 1.</b>

Return a 2-D array with 3 rows, each containing 5 values.

In [26]:
from numpy import random

x = random.choice([1,2,3,4], p=[0.5, 0.3, 0.1, 0.1], size=(25, 5))

print(x)

[[2 2 1 4 2]
 [4 2 2 1 2]
 [1 2 1 2 1]
 [1 1 1 2 3]
 [2 1 1 1 1]
 [1 1 2 4 3]
 [3 2 3 1 3]
 [1 2 1 2 1]
 [2 1 1 2 1]
 [1 2 2 1 1]
 [1 4 1 1 1]
 [3 1 1 1 3]
 [1 2 2 2 1]
 [3 1 1 1 4]
 [3 1 1 2 2]
 [1 4 3 1 3]
 [4 1 1 2 3]
 [2 4 2 1 4]
 [3 4 4 2 1]
 [1 1 2 1 2]
 [1 1 2 1 1]
 [2 1 1 1 1]
 [1 1 1 1 1]
 [1 1 2 2 2]
 [2 1 1 1 1]]


In [27]:
print("The End")

The End
