# Random Permutations

#### @jabedkhanjb

# Random Permutations of Elements

A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: <b>shuffle()</b> and <b>permutation()</b>.

# Shuffling Arrays

Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

<i><b>Randomly shuffle elements of following array:</b></i>

In [19]:
import numpy as np
from numpy import random

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)
print(arr)

[5 1 2 3 4]


<i>Shuffling name</i>

In [17]:
from numpy import random
import numpy as np
newarray = np.array(["Jabed", "Renu", "Kona"])
random.shuffle(newarray)
print(newarray)

['Kona' 'Jabed' 'Renu']


<b>The shuffle() method makes changes to the original array.</b>

# Generating Permutation of Arrays

<i><b>Generate a random permutation of elements of following array:</b></i>

In [32]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# keyword permutation()
print(f"Random Generated Array \n{random.permutation(arr)}")
print(f"\nOriginal Array \n{arr}")



Random Generated Array 
[3 2 4 5 1]

Original Array 
[1 2 3 4 5]


<i>The <b>permutation()</b> method returns a re-arranged array (and leaves the original array un-changed).</i>

In [33]:
print("The End")

The End
