# What is a Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

#### @jabedkhanjb

# Pseudo Random and True Random.

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

# Generate Random Number

NumPy offers the <b>random</b> module to work with random numbers.

<i>Generate a random integer from 0 to 100:</i>

In [11]:
from numpy import random
x = random.randint(20)
print(x)

12


# Generate Random Float

The random module's <b>rand()</b> method returns a random float between 0 and 1.

In [13]:
from numpy import random
x = random.rand()
print(x)

[0.66615318 0.76549906 0.34499157 0.22747512 0.80386701]


in this code above if you put any number, we will get the float value between 0 and 1 is that number of result.

In [15]:
from numpy import random
x = random.rand(5) # so that we will get 5 float values between 0 and 1
print(x)

[0.40538893 0.4676702  0.86836006 0.205872   0.01643998]


### Let's Generate Random Name Choice

In [58]:
import numpy as np  
from numpy import random
arr = np.array(["Renu", "Kona", "Tanha", "Shishir", "Rafsan", "Ayaan", "Jabed"])

select = random.choice(arr)
print(f"Today's Winner **{select}**")

Today's Winner **Jabed**


# Generate Random Array

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.
Integers

The <b>randint()</b> method takes a <b>size</b> parameter where you can specify the shape of an array.

<i><b>Generate a 1-D array containing 5 random integers from 0 to 100:</b></i>

In [38]:
from numpy import random
x = random.randint(100, size = (10))
print(x)

[ 5 60 74 85 75 69 72 86 82 13]


<i><b>Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:</b></i>

In [62]:
from numpy import random

x = random.randint(100, size=(3,5))
print(x)

[[80 67 36 47 28]
 [16 24 82 95 84]
 [70 34 29  0 32]]


# Floats

The <b>rand()</b> method also allows you to specify the shape of the array.

<i><b>Generate a 1-D array containing 5 random floats:</b></i>

In [66]:
from numpy import random

x = random.rand(2, 3)
print(x)

[[0.23190084 0.07555031 0.49406868]
 [0.61257319 0.15058129 0.91394055]]
